DWAPlannerROS:
  # === 로봇 기동 제한 ===
  max_vel_x: 0.3
  min_vel_x: -0.2
  max_vel_theta: 4.0
  min_vel_theta: -4.0
  min_in_place_vel_theta: 0.2

  acc_lim_x: 2.5
  acc_lim_theta: 3.0
  acc_lim_y: 0.0

  # 최소 선형 속도(정지 근처에서 떨림 방지)
  min_trans_vel: 0.1

  # === 목표 도달 허용오차 ===
  xy_goal_tolerance: 1.5          # 0.6~0.8 권장 범위
  yaw_goal_tolerance: 999.0        # 방향 무시
  latch_xy_goal_tolerance: true    # XY 들어오면 yaw 집착 완화

  # === '도착/정지' 판정 완화 ===
  trans_stopped_vel: 0.10          # m/s
  rot_stopped_vel:   0.60          # rad/s
  stop_time_buffer:  0.2           # s (이 시간 유지 시 정지로 간주)
  prune_plan:        true          

  # === 목표 부근에서 과제어 줄이기 ===
  forward_point_distance: 0.20     # 목표 근처 흔들림 완화
  path_distance_bias: 32.0
  goal_distance_bias: 18.0
  occdist_scale: 0.02              # 장애물 회피 민감도 (환경 따라 0.02~0.05)

  # === 흔들림(oscillation) 컷오프 ===
  oscillation_timeout: 5.0
  oscillation_distance: 0.2

  # === 시뮬/샘플링 ===
  sim_time: 1.7
  vx_samples: 8
  vtheta_samples: 20

  penalize_negative_x: false